# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

"""The deterministic, frozen benchmark corpus.

THREE properties, and each of them was a bug in an earlier fixture:

1. **Frozen.** The text is generated once from a seed and written to `corpus/frozen/units.jsonl`,
   which SHIPS. A benchmark whose content is regenerated by whatever version of the generator the
   tester happens to have is not a benchmark, it is two different measurements with one name. The
   generator stays in the tree so the corpus can be rebuilt deliberately, and `manifest.json`
   carries a sha256 per unit so a rebuild that changes a single character is refused rather than
   quietly measured.

2. **Every unit unique.** Shiki caches highlighted output keyed on the SOURCE STRING. A fixture
   that repeats one fence pays the highlight cost exactly once and reports the other 99 as free,
   which is how a harness measures a 300K-character thread and finds no highlighting cost in it.
   Every fence here carries its unit index in its identifiers, so no two fences in the whole corpus
   are byte-identical and the cache never hits. Unique units are only half of it: a PLAN that hands
   one unit to more than one turn restores the caching without changing a byte of the corpus, which
   is what an index clamp in `plan_rung` used to do at the top rung. `check_streamed_units_are_new`
   states that half, and the manifest is sized from the ladder so no rung can reach it.

3. **The field's own span density.** The captured 90,262-character reply carried 16,186 highlight
   spans, i.e. 5.6 characters per span, which only happens if the content is nearly all fenced
   code. 1,250 characters of prose against an 1,800-character fence lands on that; an all-fence
   fixture measures 3.47, half again as much work per character as real content. Plus a fence-free
   PREAMBLE: the capture held a flat 60 fps and exactly zero spans for its first 33,348 characters
   and started dropping frames at the first CLOSED fence, so a fixture with no such stretch cannot
   show where the onset is, only that there is one.

The escalating cycle -- reasoning@10K, code@8K, reasoning@20K, code@16K, ... -- exists because a
thread of identical turns is not what gets slow. Each cycle doubles until the cap, so a long thread
is a few enormous replies among many small ones, which is the shape of a real session.
"""

from __future__ import annotations

import hashlib
import json
import random
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Iterator, Optional

FROZEN_DIR = Path(__file__).resolve().parent / "corpus" / "frozen"
UNITS_JSONL = FROZEN_DIR / "units.jsonl"
MANIFEST_JSON = FROZEN_DIR / "manifest.json"

CORPUS_SEED = 20260819
# 2 added math. A number taken on v1 and a number taken on v2 are measurements of two different
# films, so they are not comparable and `floor_table` refuses to pool them. Bump this whenever the
# generated text changes at all, and never edit the generator without bumping it.
CORPUS_VERSION = 2

# Span density, calibrated against the field capture. See the module docstring. These are now the
# MEANS of a jittered distribution rather than fixed sizes -- see `_jitter`.
PROSE_CHARS = 1250
FENCE_CHARS = 1800
PREAMBLE_FRACTION = 0.25

# How far each block's size may wander from its mean, as a fraction. Real replies do not emit
# identically sized paragraphs and fences, and a fixture that does lets a cost that is really
# per-block masquerade as per-character (and vice versa): with every block the same size the two
# are perfectly collinear and no measurement can separate them. Jitter breaks that.
#
# Applied through the PER-UNIT rng, so unit 40 is still the same text whether it was reached by
# generating 41 units or by asking for that one. Randomised is not the same as nondeterministic:
# the corpus hash still pins every byte.
BLOCK_JITTER = 0.55

# Unit sizes wander too, around the escalating nominal. Same reason at the turn level: a thread of
# turns that are all exactly 10,000 characters is not the shape of a real session, and the rung
# planner then has no short turns to land its target on.
UNIT_JITTER = 0.35

# Tool calls per unit, as a range. The thread renders a tool group for each, which is a component
# with its own mount and update cost and which nothing in the corpus previously exercised.
TOOL_CALLS_PER_UNIT = (0, 3)

#: The stored part shape that actually renders a tool block. VERIFIED, not assumed: seeding a flat
#: `{"type": "tool-call", ...}` and an assistant-ui style `{"type": "tool-invocation", ...}` both
#: rendered their sibling text and NO tool UI, while this shape produced a "Used tool" group. A
#: corpus full of parts the app ignores looks richer and measures nothing.
TOOL_NAMES = ("web_search", "code_execution", "python", "terminal", "search_knowledge_base")

# The escalating cycle. Reasoning first because a turn's reasoning is what the pane holds open.
CYCLE_BASE = ((("reasoning", 10_000), ("code", 8_000)),)
# Doubling stops here. Without a cap the eighth cycle is a single 2.5M-character reply, which is
# not a thread, it is one document -- and it makes the 1M rung one turn deep, where every
# per-message cost this tool exists to measure is multiplied by one.
MAX_UNIT_CHARS = 320_000

# Text below `units.jsonl` ships for every rung up to and including this many characters. Beyond
# it the units are regenerated on the tester's machine and checked against the manifest hash, so
# drift is still impossible; only the bytes are not carried in the artifact.
SHIPPED_CHARS_BUDGET = 460_000


# ── the vocabulary ──────────────────────────────────────────────────
#
# Deliberately mundane. The point of the corpus is span density and uniqueness, not realism of
# meaning, and a vocabulary a reader can skim is a vocabulary a reader can spot a bug in.

_NOUNS = (
    "buffer",
    "scheduler",
    "fibre",
    "observer",
    "commit",
    "layout",
    "token",
    "shard",
    "lane",
    "chunk",
    "boundary",
    "descriptor",
    "checkpoint",
    "gradient",
    "kernel",
    "adapter",
    "window",
    "residual",
    "quantiser",
    "allocator",
    "transcript",
    "viewport",
    "sentinel",
    "digest",
)
_VERBS = (
    "reparses",
    "flushes",
    "clones",
    "invalidates",
    "schedules",
    "accumulates",
    "walks",
    "coalesces",
    "materialises",
    "spills",
    "reconciles",
    "hoists",
    "pins",
    "drains",
)
_ADJS = (
    "cumulative",
    "monotonic",
    "deferred",
    "synchronous",
    "transient",
    "bounded",
    "retained",
    "speculative",
    "interleaved",
    "hysteretic",
    "collinear",
    "saturating",
)
_CONNECTIVES = (
    "which means",
    "so in practice",
    "and therefore",
    "but only when",
    "except that",
    "as long as",
    "provided that",
    "which is why",
)
_LANGS = ("python", "typescript", "rust", "go", "c")
# Short names for code. See _fence: span density is per TOKEN, so long names dilute it.
_SHORT = (
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "n",
    "p",
    "q",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "acc",
    "buf",
    "idx",
    "key",
    "len",
    "map",
    "ptr",
    "res",
    "tmp",
)

# ── math ────────────────────────────────────────────────────────────
#
# Corpus v1 contained not one dollar sign across 519,859 characters, which made every math cost in
# the app unmeasurable by construction. That is not a hypothetical gap: `preprocessLaTeX` was
# measured as a real cost in isolation and then as an exact NULL in the browser, and the reason was
# that the fixture gave it nothing to do. A benchmark that cannot see a cost cannot be used to
# argue the cost is not there.
#
# Both delimiter families are here on purpose. `$...$` and `$$...$$` are what remark-math consumes
# directly; `\(...\)` and `\[...\]` are what `preprocessLaTeX` exists to REWRITE into that form, so
# a corpus carrying only the first kind exercises the renderer while leaving the preprocessor's
# actual work uncovered.
_MATH_OPS = ("+", "-", "\\cdot", "\\times", "\\oplus")
_MATH_RELS = ("=", "\\le", "\\ge", "\\approx", "\\equiv")
_MATH_FUNCS = ("\\log", "\\exp", "\\sin", "\\cos", "\\tanh")
_MATH_GREEK = (
    "\\alpha",
    "\\beta",
    "\\gamma",
    "\\delta",
    "\\theta",
    "\\lambda",
    "\\mu",
    "\\sigma",
    "\\phi",
    "\\omega",
)

# Chance that a non-preamble prose BLOCK is a display-math block instead.
#
# Math takes prose's slot rather than being appended alongside it, and is drawn from the same
# jittered size distribution. That keeps the prose/fence alternation exactly as it was: same number
# of fences, same fence sizes, so the Shiki span density the whole corpus is calibrated to is
# untouched by construction rather than by a re-tuning nobody would re-check.
MATH_BLOCK_PROB = 0.16

# Chance that a sentence in a non-preamble prose block carries an inline expression. Inline math is
# the common case in real chat replies, and it is the one that interleaves with text rather than
# sitting in its own block, which is a different path through the markdown pipeline.
#
# Inline math is spent from the prose block's own character budget, for the same reason as above.
INLINE_MATH_PROB = 0.22

# The PREAMBLE stays pure prose, deliberately. Its whole job is to be the stretch that builds no
# spans and holds 60 fps, so the onset of cost has somewhere to be visible against. Putting math in
# it would give the preamble a rendering cost and destroy the only fence-free, math-free baseline
# the film has.


@dataclass(frozen = True)
class Unit:
    """One assistant turn's worth of content."""

    index: int
    kind: str  # "reasoning" | "code"
    reasoning: str  # goes out as delta.reasoning_content
    content: str  # goes out as delta.content
    chars: int
    sha256: str
    #: Stored tool-call parts for this turn, in the shape the app renders. Not counted in `chars`:
    #: `chars` is the rung's size axis and must stay comparable with every earlier measurement,
    #: while a tool call's cost is a mount, not a character count. Reported separately.
    tool_calls: tuple = ()

    @property
    def tool_call_count(self) -> int:
        return len(self.tool_calls)

    def as_row(self) -> dict:
        return {
            "index": self.index,
            "kind": self.kind,
            "chars": self.chars,
            "sha256": self.sha256,
            "reasoning": self.reasoning,
            "content": self.content,
            "tool_calls": list(self.tool_calls),
        }

    def clipped_to(self, chars: int) -> "Unit":
        """A prefix of this unit at WHOLE BLOCK boundaries, for a rung smaller than one turn.

        The smallest rung is 1K tokens, about 4,000 characters, and the escalating cycle's first
        turn is 10,000. Something has to give, and clipping the first turn is the only option that
        leaves the cycle itself intact for every rung above.

        Blocks, not characters, and the reason is a rendering path rather than tidiness: the parts
        are separated by blank lines and every fence is one whole part, so a block-aligned prefix
        can never end inside a fence. A character-aligned one can, and an unclosed fence is a
        DIFFERENT Streamdown path (the incomplete-fence branch) with a different cost, so the
        smallest rung would have been measuring something no other rung measures.
        """
        if chars >= self.chars:
            return self

        def take(text: str, budget: int) -> str:
            blocks = text.split("\n\n")
            out: list[str] = []
            size = 0
            for b in blocks:
                if out and size + len(b) + 2 > budget:
                    break
                out.append(b)
                size += len(b) + 2
            return "\n\n".join(out)

        # Keep the unit's own reasoning/content split, so a clipped turn has the same shape as a
        # whole one and the smallest rung is not accidentally all-visible or all-reasoning.
        reasoning_budget = max(1, int(chars * (len(self.reasoning) / self.chars)))
        reasoning = take(self.reasoning, reasoning_budget)
        content = take(self.content, max(1, chars - len(reasoning)))
        text = reasoning + content
        return Unit(
            index = self.index,
            kind = self.kind,
            reasoning = reasoning,
            content = content,
            chars = len(text),
            # A DIFFERENT digest, deliberately. A clipped unit is not the frozen unit and must not
            # be checked against its hash or reported under it.
            sha256 = "clip:"
            + hashlib.sha256(f"{self.sha256}\x00{chars}".encode("utf-8")).hexdigest(),
            # Tool calls survive clipping. They carry no `chars` weight, so dropping them would
            # silently remove a whole component from exactly the rung -- the smallest -- that every
            # growth ratio is taken against.
            tool_calls = self.tool_calls,
        )

    @classmethod
    def from_row(cls, row: dict) -> "Unit":
        return cls(
            index = row["index"],
            kind = row["kind"],
            reasoning = row["reasoning"],
            content = row["content"],
            chars = row["chars"],
            sha256 = row["sha256"],
            tool_calls = tuple(row.get("tool_calls") or ()),
        )


# ── generation ──────────────────────────────────────────────────────


def _expression(rng: random.Random, salt: str, terms: int) -> str:
    """One LaTeX expression body, unique to `salt`.

    Salted in a SUBSCRIPT rather than a comment, for the same reason `_fence` salts identifiers:
    KaTeX caches nothing today, but Streamdown memoises rendered blocks on their source, and a
    salt that a later normalisation pass could strip would silently restore the caching and halve a
    measured cost without changing a number in the report.
    """
    parts = [f"{rng.choice(_MATH_GREEK)}_{{{salt}}}", rng.choice(_MATH_RELS)]
    for i in range(terms):
        if i:
            parts.append(rng.choice(_MATH_OPS))
        shape = rng.random()
        if shape < 0.30:
            parts.append(
                f"\\frac{{{rng.choice(_MATH_GREEK)}^{{{rng.randint(2, 9)}}}}}"
                f"{{{rng.randint(1, 99)} {rng.choice(_MATH_GREEK)}}}"
            )
        elif shape < 0.50:
            parts.append(
                f"\\sum_{{{rng.choice(_SHORT)}={rng.randint(0, 3)}}}^{{{rng.randint(4, 99)}}} "
                f"{rng.choice(_MATH_GREEK)}_{{{rng.choice(_SHORT)}}}"
            )
        elif shape < 0.65:
            parts.append(f"\\sqrt{{{rng.choice(_MATH_GREEK)} {rng.randint(2, 99)}}}")
        elif shape < 0.80:
            parts.append(
                f"{rng.choice(_MATH_FUNCS)}\\left({rng.choice(_MATH_GREEK)}"
                f"^{{{rng.randint(2, 5)}}}\\right)"
            )
        else:
            parts.append(f"{rng.choice(_MATH_GREEK)}^{{{rng.randint(2, 9)}}}")
    return " ".join(parts)


def _inline_math(rng: random.Random, salt: str) -> str:
    """One inline expression, in whichever delimiter family this draw lands on.

    `\\(...\\)` is not markdown's own syntax: it reaches the renderer only if `preprocessLaTeX`
    rewrites it first, so this is the draw that covers the preprocessor rather than the renderer.
    """
    body = _expression(rng, salt, rng.randint(1, 2))
    return f"$ {body} $" if rng.random() < 0.65 else f"\\( {body} \\)"


def _sentence(
    rng: random.Random,
    salt: str,
    *,
    math: bool = False,
) -> str:
    tail = f" where {_inline_math(rng, salt)} holds" if math else ""
    return (
        f"The {rng.choice(_ADJS)} {rng.choice(_NOUNS)} {rng.choice(_VERBS)} the "
        f"{rng.choice(_ADJS)} {rng.choice(_NOUNS)}_{salt}, {rng.choice(_CONNECTIVES)} the "
        f"{rng.choice(_NOUNS)} stays {rng.choice(_ADJS)}{tail}."
    )


def _prose(
    rng: random.Random,
    target: int,
    salt: str,
    *,
    math: bool = False,
) -> str:
    """`target` characters of fence-free prose. No Shiki span will be built over any of it.

    With `math`, a share of the sentences carry an inline expression. Those characters are spent
    from `target` like any other, so a prose block is the same size whether or not it has math in
    it and the corpus keeps the block-size distribution it was calibrated with.
    """
    out: list[str] = []
    size = 0
    while size < target:
        para: list[str] = []
        for _ in range(rng.randint(3, 6)):
            s = _sentence(rng, salt, math = math and rng.random() < INLINE_MATH_PROB)
            para.append(s)
            size += len(s) + 1
        out.append(" ".join(para))
        size += 2
        if size >= target:
            break
    return "\n\n".join(out)


def _math_block(rng: random.Random, target: int, salt: str) -> str:
    """`target` characters of display math, as a run of blocks with prose between them.

    Not one enormous equation: a reply with math in it is a handful of displayed lines threaded
    through explanation, and a single block would measure the cost of one very large KaTeX tree
    rather than the cost of many, which is the shape that actually accumulates in a long thread.
    """
    out: list[str] = []
    size = 0
    i = 0
    while size < target:
        body = _expression(rng, f"{salt}m{i}", rng.randint(3, 6))
        block = f"$$\n{body}\n$$" if rng.random() < 0.65 else f"\\[\n{body}\n\\]"
        out.append(block)
        size += len(block) + 2
        i += 1
        if size >= target:
            break
        gloss = _prose(rng, _jitter(rng, 260, floor = 60), f"{salt}g{i}", math = True)
        out.append(gloss)
        size += len(gloss) + 2
    return "\n\n".join(out)


def _fence(
    rng: random.Random,
    target: int,
    salt: str,
    lang: Optional[str] = None,
) -> str:
    """`target` characters of fenced code, unique to `salt`.

    The salt is in every identifier, not just in a comment. Shiki keys its cache on the whole
    source string, so a comment would be enough to miss the cache -- but a highlighter that ever
    learns to normalise comments would silently restore the caching and halve the measured cost
    without changing a number in the report. Identifiers cannot be normalised away.
    """
    lang = lang or rng.choice(_LANGS)
    lines = [f"```{lang}"]
    size = len(lines[0]) + 1
    i = 0
    # SHORT identifiers and dense punctuation, because the density target is a SPAN count, not a
    # character count. Long descriptive names are cheap to highlight per character: the field
    # capture ran at 5.6 characters per span, and a first version of this generator with
    # `cumulative_buffer_0007_12`-style names measured 10.1, i.e. half the highlighter work per
    # character of the content it is standing in for. Real code is mostly operators.
    r = rng.randint

    def v() -> str:
        # A MIX of short and long names. All-short measured 3.95 characters per span against the
        # field's 5.6 and all-long measured 10.1, so neither extreme stands in for real code. The
        # mix is the tuning knob for the offline proxy; the number that actually gets reported is
        # the span density MEASURED in the DOM at run time, because Shiki merges adjacent
        # same-scope tokens and no offline count can predict that exactly.
        return rng.choice(_SHORT) if rng.random() < 0.55 else rng.choice(_NOUNS)

    while size < target:
        # ONE salted identifier per line is all the uniqueness Shiki's source-keyed cache needs,
        # and it leaves the rest of the line free to be dense.
        u = f"{rng.choice(_SHORT)}{salt}{i}"
        if lang == "python":
            line = (
                f"    {u}={v()}[{r(0,9)}]*{r(2,99)}-{v()}({v()},{v()})+{v()}[{r(0,9)}:{r(1,9)}]"
                f";{v()}={v()}%{r(2,9)} if {v()}>{r(1,99)} else {v()}|{r(1,7)}"
            )
        elif lang == "typescript":
            line = (
                f"  const {u}={{a:{v()}[{r(0,9)}],b:{v()}({v()},{r(1,99)}),c:{v()}?{v()}:"
                f"{r(0,9)}}};{v()}={v()}&{r(1,7)}|{v()}<<{r(1,7)};"
            )
        elif lang == "rust":
            line = (
                f"    let {u}:u64={v()}[{r(0,9)}]^{v()}({v()},{r(1,99)})&{r(1,255)};"
                f"{v()}={v()}.iter().map(|x|x*{r(2,99)}).sum::<u64>();"
            )
        elif lang == "go":
            line = (
                f"\t{u}:={v()}[{r(0,9)}]+{v()}({v()},{r(1,99)})*{r(2,99)};"
                f"{v()},{v()}={v()}%{r(2,9)},{v()}>>{r(1,7)}"
            )
        else:
            line = (
                f"    uint64_t {u}={v()}[{r(0,9)}]|({v()}({v()},{r(1,99)})&0x{r(16,255):02x})"
                f";{v()}=*{v()}++^{r(1,255)};"
            )
        lines.append(line)
        size += len(line) + 1
        i += 1
    lines.append("```")
    return "\n".join(lines)


def _jitter(
    rng: random.Random,
    mean: int,
    spread: float = BLOCK_JITTER,
    floor: int = 80,
) -> int:
    """A size around `mean`, never below `floor`.

    Uniform on [1-spread, 1+spread] rather than lognormal: the point is to decorrelate block size
    from block count, and a symmetric spread does that while keeping the MEAN exactly where the
    span-density calibration put it. A skewed distribution would quietly move the mean and with it
    the characters-per-span figure the whole corpus is tuned to.
    """
    return max(floor, int(mean * (1.0 + rng.uniform(-spread, spread))))


def _body(rng: random.Random, target: int, salt: str, *, preamble: bool) -> str:
    """Preamble, then a jittered prose/fence alternation, to `target` characters."""
    parts: list[str] = []
    size = 0
    if preamble:
        want = int(target * PREAMBLE_FRACTION)
        head = _prose(rng, want, f"{salt}p")
        parts.append(head)
        size += len(head) + 2
    while size < target:
        # Math takes the prose slot rather than being added alongside it, and is drawn from the
        # same size distribution, so the fence blocks keep their count and their sizes and the
        # span-density calibration in the module docstring still holds.
        want = _jitter(rng, PROSE_CHARS)
        if rng.random() < MATH_BLOCK_PROB:
            p = _math_block(rng, want, f"{salt}{len(parts)}")
        else:
            p = _prose(rng, want, f"{salt}{len(parts)}", math = True)
        parts.append(p)
        size += len(p) + 2
        if size >= target:
            break
        f = _fence(rng, _jitter(rng, FENCE_CHARS), f"{salt}{len(parts)}")
        parts.append(f)
        size += len(f) + 2
    return "\n\n".join(parts)


def _tool_calls(rng: random.Random, salt: str) -> list[dict]:
    """Zero to three tool calls for one turn, in the part shape the app actually renders."""
    low, high = TOOL_CALLS_PER_UNIT
    out: list[dict] = []
    for i in range(rng.randint(low, high)):
        name = rng.choice(TOOL_NAMES)
        query = _prose(rng, _jitter(rng, 220, floor = 40), f"{salt}t{i}q").replace("\n", " ")
        result = _prose(rng, _jitter(rng, 900, floor = 120), f"{salt}t{i}r")
        args = (
            {"query": query} if name in ("web_search", "search_knowledge_base") else {"code": query}
        )
        out.append(
            {
                "type": "tool-call",
                "toolCallId": f"call_{salt}_{i}",
                "toolName": name,
                "argsText": json.dumps(args),
                "args": args,
                "state": "result",
                "result": result,
            }
        )
    return out


def _unit_targets(index: int) -> tuple[str, int]:
    """(kind, target chars) for unit `index` of the escalating cycle."""
    cycle = index // 2
    slot = index % 2
    base = 10_000 if slot == 0 else 8_000
    kind = "reasoning" if slot == 0 else "code"
    nominal = min(MAX_UNIT_CHARS, base * (2**cycle))
    # Jittered around the nominal, deterministic in `index` alone so the escalating shape survives
    # while no two turns are the same size. A separate RNG from the body's, so changing block
    # jitter does not reshuffle which turns are large.
    rng = random.Random((index * 6_364_136_223_846_793_005) ^ 0x5DEECE66D)
    return kind, max(1_500, min(MAX_UNIT_CHARS, _jitter(rng, nominal, UNIT_JITTER, floor = 1_500)))


def generate_unit(index: int, seed: int = CORPUS_SEED) -> Unit:
    """Unit `index`, deterministic in (seed, index) alone.

    Seeded per unit and not per corpus, so unit 40 is the same text whether it was reached by
    generating 41 units or by asking for that one. A corpus-level RNG would make the 1M rung's
    early turns differ from the 1K rung's, and then two rungs would not share a prefix and the
    growth curve would be over two different corpora.
    """
    rng = random.Random((seed * 1_000_003) ^ (index * 2_654_435_761))
    kind, target = _unit_targets(index)
    salt = f"{index:04d}"
    if kind == "reasoning":
        # A reasoning turn: most of the mass arrives as delta.reasoning_content, so the cumulative
        # <think> re-parse in the chat adapter is what pays for it.
        reasoning = _body(rng, int(target * 0.8), f"r{salt}", preamble = True)
        content = _body(rng, int(target * 0.2), f"a{salt}", preamble = False)
    else:
        # A code turn: the mass is visible content, so the cost lands on Streamdown and Shiki.
        reasoning = _prose(rng, 1_200, f"r{salt}")
        content = _body(rng, target, f"a{salt}", preamble = False)
    tools = tuple(_tool_calls(rng, salt))
    chars = len(reasoning) + len(content)
    digest = hashlib.sha256(
        (
            f"{index}\x00{kind}\x00{reasoning}\x00{content}\x00" + json.dumps(tools, sort_keys = True)
        ).encode("utf-8")
    ).hexdigest()
    return Unit(
        index = index,
        kind = kind,
        reasoning = reasoning,
        content = content,
        chars = chars,
        sha256 = digest,
        tool_calls = tools,
    )


def units_for_chars(total_chars: int, seed: int = CORPUS_SEED) -> list[Unit]:
    """The shortest prefix of the cycle whose characters reach `total_chars`."""
    out: list[Unit] = []
    size = 0
    index = 0
    while size < total_chars:
        u = generate_unit(index, seed)
        out.append(u)
        size += u.chars
        index += 1
        if index > 4096:
            raise RuntimeError("corpus cycle did not reach the requested size")
    return out


# ── freezing and loading ────────────────────────────────────────────


def freeze(
    max_chars: int = SHIPPED_CHARS_BUDGET,
    seed: int = CORPUS_SEED,
    out_dir: Path = FROZEN_DIR,
) -> dict:
    """Write `units.jsonl` and `manifest.json`. Run deliberately; never on a benchmark run."""
    out_dir.mkdir(parents = True, exist_ok = True)
    shipped = units_for_chars(max_chars, seed)
    # The manifest covers every unit any rung can reach, including the ones whose text is not
    # shipped, so a regenerated unit at the 1M rung is still checked byte for byte. SIZED FROM THE
    # LADDER, by `manifest_unit_count`, rather than from a bare character budget: the streamed turn
    # and its follow-ups live PAST the seeded prefix, and a manifest that stops where the prefix
    # stops leaves them nothing to point at.
    all_units = [generate_unit(i, seed) for i in range(manifest_unit_count(seed))]
    with (out_dir / "units.jsonl").open("w", encoding = "utf-8") as fh:
        for u in shipped:
            fh.write(json.dumps(u.as_row(), ensure_ascii = False) + "\n")
    manifest = {
        "corpus_version": CORPUS_VERSION,
        "seed": seed,
        "prose_chars": PROSE_CHARS,
        "fence_chars": FENCE_CHARS,
        "preamble_fraction": PREAMBLE_FRACTION,
        "math_block_prob": MATH_BLOCK_PROB,
        "inline_math_prob": INLINE_MATH_PROB,
        "max_unit_chars": MAX_UNIT_CHARS,
        "shipped_units": len(shipped),
        "shipped_chars": sum(u.chars for u in shipped),
        "units": [
            {"index": u.index, "kind": u.kind, "chars": u.chars, "sha256": u.sha256}
            for u in all_units
        ],
    }
    manifest["corpus_hash"] = corpus_hash(manifest)
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent = 2, ensure_ascii = False) + "\n", encoding = "utf-8"
    )
    return manifest


def corpus_hash(manifest: dict) -> str:
    """One hash over the generator's parameters and every unit digest.

    Includes the parameters, not only the unit hashes, because two corpora with the same text and
    different declared densities would otherwise compare as identical.
    """
    h = hashlib.sha256()
    for key in (
        "corpus_version",
        "seed",
        "prose_chars",
        "fence_chars",
        "preamble_fraction",
        "math_block_prob",
        "inline_math_prob",
        "max_unit_chars",
    ):
        h.update(f"{key}={manifest[key]}\x00".encode("utf-8"))
    for u in manifest["units"]:
        h.update(f"{u['index']}:{u['sha256']}\x00".encode("utf-8"))
    return h.hexdigest()


class Corpus:
    """The frozen corpus, with every unit checked against the manifest before it is used."""

    def __init__(self, manifest: dict, shipped: dict[int, Unit], seed: int) -> None:
        self.manifest = manifest
        self.seed = seed
        self._shipped = shipped
        self._expected = {u["index"]: u["sha256"] for u in manifest["units"]}
        self.corpus_hash = manifest["corpus_hash"]
        self.regenerated: list[int] = []

    @classmethod
    def load(cls, frozen_dir: Optional[Path] = None) -> "Corpus":
        # Through the resource loader, NOT a filesystem path. Inside `studiobench.pyz` the frozen
        # corpus is a zip member and every Path built from __file__ points at something that
        # cannot exist; the built artifact's own --doctor is what caught it.
        from ..runtime import resources

        if frozen_dir is not None:
            manifest_path = Path(frozen_dir) / "manifest.json"
            if not manifest_path.exists():
                raise FileNotFoundError(f"no frozen manifest at {manifest_path}")
            raw_manifest = manifest_path.read_text(encoding = "utf-8")
            raw_units = ""
            units_path = Path(frozen_dir) / "units.jsonl"
            if units_path.exists():
                raw_units = units_path.read_text(encoding = "utf-8")
        else:
            try:
                raw_manifest = resources.read_text("fixture/corpus/frozen/manifest.json")
            except (FileNotFoundError, OSError) as exc:
                raise FileNotFoundError(
                    "the frozen corpus is not in this build. Run "
                    "`python -m tests.studio.studiobench.fixture.corpus --freeze` to build it."
                ) from exc
            try:
                raw_units = resources.read_text("fixture/corpus/frozen/units.jsonl")
            except (FileNotFoundError, OSError):
                raw_units = ""
        manifest = json.loads(raw_manifest)
        recomputed = corpus_hash(manifest)
        if recomputed != manifest.get("corpus_hash"):
            raise ValueError(
                f"the frozen manifest's own corpus_hash does not match its contents "
                f"({manifest.get('corpus_hash')} declared, {recomputed} recomputed). The corpus "
                "has been edited by hand; rebuild it with --freeze."
            )
        shipped: dict[int, Unit] = {}
        for line in raw_units.splitlines():
            line = line.strip()
            if line:
                u = Unit.from_row(json.loads(line))
                shipped[u.index] = u
        return cls(manifest, shipped, manifest["seed"])

    def unit(self, index: int) -> Unit:
        """Unit `index`, from the shipped text if it is there and regenerated if it is not.

        EITHER WAY it is checked against the manifest digest. A regenerated unit that does not
        match is a hard failure: it means the generator in this tree does not produce the corpus
        this artifact claims to measure, and every number after it would be from a different
        fixture with the same name.
        """
        u = self._shipped.get(index)
        if u is None:
            u = generate_unit(index, self.seed)
            self.regenerated.append(index)
        expected = self._expected.get(index)
        if expected is None:
            raise KeyError(f"unit {index} is outside the frozen manifest")
        if u.sha256 != expected:
            raise ValueError(
                f"corpus unit {index} does not match the frozen manifest "
                f"(expected {expected[:16]}, got {u.sha256[:16]}). The generator has drifted; "
                "this tree cannot reproduce the shipped corpus."
            )
        return u

    def units_for_chars(self, total_chars: int) -> list[Unit]:
        out: list[Unit] = []
        size = 0
        index = 0
        while size < total_chars:
            u = self.unit(index)
            out.append(u)
            size += u.chars
            index += 1
        return out

    def iter_units(self) -> Iterator[Unit]:
        for entry in self.manifest["units"]:
            yield self.unit(entry["index"])


# ── rungs ───────────────────────────────────────────────────────────

RUNGS: dict[str, int] = {
    "1K": 1_000,
    "10K": 10_000,
    "100K": 100_000,
    "500K": 500_000,
    "1M": 1_000_000,
}

# The PROVISIONAL ratio used to size the corpus before anything has been tokenised. It is never
# reported: `chars_per_token` in every row is the MEASURED one, and it is measured per rung.
PROVISIONAL_CHARS_PER_TOKEN = 4.0

# How much of the last turn STREAMS, at every rung. See the long note in `plan_rung`.
#
# Sized from the film, not chosen round: the quick scene's during-generation slots occupy the
# first 16 s and the first after-generation slot opens at 22.5 s, so the stream has to finish
# inside roughly 20 s. At the field cadence of 24 characters every 73 ms -- 328.8 chars/s -- that
# is about 6,500 characters. Rounded DOWN so the stream reliably drains before the first action
# that claims the reply is complete, rather than finishing exactly as it starts.
STREAM_TAIL_CHARS = 6_000

# How many turns actually stream per cell: the opening one plus the follow-ups the `send_turn`
# action sends mid-film. They SHARE the budget above rather than each getting it, so three turns
# and one turn take the same wall clock. Three because the corpus alternates reasoning-heavy and
# code-heavy units, so three consecutive turns are guaranteed to cover both kinds.
STREAM_TURNS = 3

# Each follow-up's size. Small on purpose: the follow-ups exist to sample "what does a chunk cost
# given what is already on screen" at two more points inside the cell, not to add mass.
FOLLOW_UP_CHARS = 1_500

# Below this the rung streams ONCE. Three turns need about 9,000 characters of budget and the 1K
# rung is 4,000 characters in total, so splitting it three ways produced an opening stream that
# drained in four seconds -- shorter than the during-generation slots timed against it -- and a
# rung 40% over its own target. A small rung is allowed to be a single exchange, which is also
# what a 1K-token conversation actually is.
MULTI_TURN_MIN_CHARS = 20_000

# The largest characters-per-token the FROZEN CORPUS is sized for, which is not the same number as
# the provisional ratio used to plan a rung. `plan_rung` takes a measured ratio, and a corpus sized
# at exactly the provisional 4.0 has no material left the moment a machine measures 4.1. A quarter
# of headroom costs a handful of extra manifest entries -- the text of an unshipped unit is
# regenerated only when a rung actually reaches it -- and buys every ratio the seeder can plausibly
# report. Past it `plan_rung` refuses rather than degrades.
MANIFEST_CHARS_PER_TOKEN = 5.0


def manifest_unit_count(
    seed: int = CORPUS_SEED, chars_per_token: float = MANIFEST_CHARS_PER_TOKEN
) -> int:
    """How many units the frozen manifest must carry, DERIVED FROM THE LADDER.

    The corpus used to be sized by a bare `RUNGS["1M"] * 4` character budget, which is exactly the
    largest rung's seeded target and therefore one unit short of what the largest rung needs. The
    streamed turn is the unit AFTER the seeded prefix and each follow-up is one after that, so the
    top rung's stream ran off the end of the manifest and a `min(index, last_index)` clamp folded
    all three onto the final unit: the opening stream re-sent text already seeded, both follow-ups
    were byte-identical, and every fence in them hit Shiki's source-keyed cache instead of missing
    it. The rung that exists to be the most expensive one on the ladder was measured as the
    cheapest per character, and nothing failed.

    So the ladder sizes the corpus and not the reverse: the longest seeded prefix any rung can ask
    for, plus one unit per streamed turn beyond it.
    """
    prefix = len(units_for_chars(int(max(RUNGS.values()) * chars_per_token), seed))
    return prefix + STREAM_TURNS


@dataclass
class RungPlan:
    """What a rung is made of, and how much of it streams rather than being seeded."""

    rung: str
    target_tokens: int
    target_chars: int
    seeded_units: list[Unit] = field(default_factory = list)
    streamed_unit: Optional[Unit] = None
    #: Further turns streamed DURING the film by the `send_turn` action. They come out of the same
    #: fixed streaming budget as the first, split between them, so more turns cost no wall clock.
    follow_up_units: list[Unit] = field(default_factory = list)

    @property
    def seeded_chars(self) -> int:
        return sum(u.chars for u in self.seeded_units)

    @property
    def streamed_chars(self) -> int:
        return self.streamed_unit.chars if self.streamed_unit else 0

    @property
    def follow_up_chars(self) -> int:
        return sum(u.chars for u in self.follow_up_units)

    @property
    def total_chars(self) -> int:
        # The follow-ups are part of the rung's mass: they are streamed INTO the thread during the
        # film and are on screen for most of it. Leaving them out understated every rung by the
        # follow-up budget, which at the 1K rung is most of the rung.
        return self.seeded_chars + self.streamed_chars + self.follow_up_chars


def dollarise(text: str, salt: str) -> str:
    """Give `text` the CURRENCY AND SHELL dollars a real reply has, deterministically.

    WHAT THIS IS FOR, AND WHAT IT IS NO LONGER FOR. This was written when the frozen corpus
    contained zero `$`, zero `\\[` and zero `\\(` across all 519,859 characters, so that
    `preprocessLaTeX` -- which runs on the whole reply once per animation frame -- always took its
    cheap path. That path is an early return after `text.includes("$")` fails
    (`studio/frontend/src/lib/latex.ts`), and the two regimes are an order of magnitude apart:
    measured over one 96,000 character reply, 15.3 ms against 281.3 ms.

    CORPUS v2 CHANGED THAT AND THIS DOCSTRING WOULD OTHERWISE LIE. The frozen corpus now carries
    well-formed LaTeX throughout, and the streamed unit is drawn from it, so the streamed reply
    already contains `$` without this flag: 10 of them at the 10K rung and 6 at 100K, measured.
    The early return is therefore already defeated by default, and the claim that the expensive
    regime "has never been exercised" is dead. Anyone reaching for this flag to reach that regime
    does not need it any more.

    WHAT IT STILL DOES, which is narrower and worth stating exactly. The early return is keyed on
    the reply BEING PROCESSED -- `preprocessLaTeX(displayText)` is called per message
    (`components/assistant-ui/markdown-text.tsx`) -- and past it the cost is the `CURRENCY_REGEX`
    pass, whose callback has three branches: skip inside a code region, skip inside a math region
    just created from `\\(...\\)`, and escape everything else. v2's dollars are well-formed math,
    so they take the SKIP branches. The dollars added here are deliberately not math: `$HOME/...`
    inside fences exercises the code-region exclusion, and `$12.99` in prose exercises the escape
    branch and `hasInlineMathCloser`. That is the false-positive half of the function, and it is
    the half that rewrites the string rather than leaving it alone.

    So the two mechanisms are complementary rather than redundant: v2 puts renderable math in the
    SEEDED thread and exercises the renderer, and this puts malformed-on-purpose dollars in the
    turn that STREAMS and exercises the heuristics, per chunk, on the path a streaming-cost metric
    measures. Expect a far smaller effect from this flag than the 15.3-to-281.3 figure above,
    because that transition now happens without it.

    Applied to the STREAMED unit only, and never to the frozen corpus on disk: the frozen units
    and their hashes are exactly what they were, so a run with this off is byte-identical to a run
    of the same corpus version without it. A run with it on records the fact in its payload,
    because a corpus difference that is not in the payload is a difference two runs will be
    compared across without knowing.
    """
    lines = text.split("\n")
    out: list[str] = []
    fenced = False
    for index, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith("```") or stripped.startswith("~~~"):
            fenced = not fenced
            out.append(line)
            continue
        # Inside a fence, shell-shaped lines. Outside it, prices in prose. Both are what a real
        # answer contains, and they exercise different branches: the code-region scan has to
        # EXCLUDE the first and the currency heuristic has to escape the second.
        if fenced and index % 11 == 0:
            out.append(f"{line}  # $HOME/{salt}{index} costs $1{index % 10}.99")
        elif not fenced and line and index % 17 == 0:
            out.append(f"{line} It costs ${index % 9}{index % 10}.99 or ${index % 7},200 a year.")
        else:
            out.append(line)
    return "\n".join(out)


def _too_small(rung: str, chars_per_token: float, last_index: int, what: str) -> ValueError:
    """The one message for every way a rung can outgrow the frozen corpus.

    Deliberately an ERROR and not a clamp. The clamp it replaces is how a 1M rung came to stream
    the same unit three times and report the cheapest per-character cost on the ladder, and a
    benchmark that quietly measures something smaller than it says is worse than one that stops.
    """
    return ValueError(
        f"the frozen corpus is too small for the {rung} rung at {chars_per_token} chars per "
        f"token: {what} runs past the manifest, which ends at index {last_index}. Re-freeze with "
        "`python -m tests.studio.studiobench.fixture.corpus --freeze` after raising "
        "MANIFEST_CHARS_PER_TOKEN, and note that a re-freeze changes corpus_hash and so ends "
        "comparability with everything measured before it."
    )


def _tail_not_deliverable(
    rung: str,
    requested: int,
    source_index: int,
    deliverable: int,
    thread_chars: int,
    target_chars: int,
) -> ValueError:
    """An explicit `--stream-tail-chars` the corpus cannot actually deliver.

    Deliberately an ERROR and not a shortfall field, for the same reason `_too_small` is. The
    quantity this flag exists to vary is the ONLY variable in a reply-length experiment, so a run
    that silently measures a fraction of it has no honest reading at all -- there is nothing to
    caveat, the axis simply did not move.

    TWO EFFECTS COMPOUND HERE and the message names both, because fixing only the one you noticed
    leaves the other. The tail is one corpus unit and `clipped_to` returns the unit unchanged when
    the ask exceeds it, so delivery is capped at that unit's size. And asking for MORE tail lowers
    that cap rather than raising it: a bigger tail shrinks `seed_target`, which moves the streamed
    turn to a lower index, and the corpus escalates in size, so the ceiling falls as the request
    rises. At the extreme the seeded prefix is evacuated entirely and the rung's own thread goes
    with it, while the cell keeps its rung label, its rung weight and its place in the table.

    Measured before this guard existed: `--rungs 100K --stream-tail-chars 400000` delivered 15,405
    characters of the 400,000 asked for (3.9%) on a thread of 18,122 characters against the rung's
    397,755 (4.6%), and `--assert-liveness` returned `0 scene problems, 0 missed slots`, exit 0,
    byte-identical to the default run -- because a saturated tail drains FASTER than the film it
    was supposed to outlast, so the one check that could have noticed goes quieter as the input
    gets more wrong.
    """
    return ValueError(
        f"the frozen corpus cannot deliver a {requested:,} character streamed tail at the {rung} "
        f"rung: the streamed turn is unit {source_index}, which is {deliverable:,} characters, so "
        f"the reply would be {deliverable / requested:.1%} of the one asked for. Asking for more "
        f"tail makes this worse rather than better, because the seeded prefix shrinks to pay for "
        f"it and the streamed turn moves to a smaller unit -- here the thread would collapse to "
        f"{thread_chars:,} characters against the rung's {target_chars:,}, while still being "
        f"recorded, weighted and reported as {rung}. Ask for less, or move the same request to a "
        f"higher rung. NOT 'at most {deliverable:,}': that is this unit's size at THIS request, "
        f"and the ceiling RISES as the request falls, because a smaller tail leaves a longer "
        f"seeded prefix which draws the streamed turn from a larger unit. Lower the ask until "
        f"this stops firing rather than reading a maximum off this line."
    )


def unit_text(unit: Unit) -> str:
    """Everything a unit puts on screen, in the order it arrives."""
    return unit.reasoning + unit.content


def check_streamed_units_are_new(plan: RungPlan) -> None:
    """Every streamed turn must be material the thread has not seen. Raises when it is not.

    This is the corpus's whole reason for existing, restated at the level of a rung plan. Shiki
    caches highlighted output keyed on the SOURCE STRING, so a fence that has already been rendered
    once in this thread costs nothing the second time. Property 2 in the module docstring keeps
    every unit in the corpus distinct; it says nothing about a PLAN that hands the same unit to
    three turns, which is exactly what the index clamp used to do at the top rung.

    Checked as a PREFIX relation and not equality, because the streamed turns are clipped and a
    clipped unit is a prefix of the unit it came from. Two turns clipped from one unit are not
    equal and would pass an equality check while sharing every fence they have.

    Run on every plan rather than only in a test: this is not a property to discover afterwards
    from a table of numbers that came out lower than they should have.
    """
    streamed: list[tuple[str, str]] = []
    if plan.streamed_unit is not None:
        streamed.append(("streamed", unit_text(plan.streamed_unit)))
    for i, unit in enumerate(plan.follow_up_units):
        streamed.append((f"follow_up[{i}]", unit_text(unit)))

    def fail(what: str, a: str, b: str) -> None:
        raise ValueError(
            f"rung {plan.rung}: {a} and {b} {what}. A streamed turn that repeats material already "
            "on screen hits Shiki's source-keyed cache instead of missing it, so the rung reports "
            "less work per character than it does. The corpus is too small for this ladder; "
            "re-freeze it with `--freeze`."
        )

    seeded = [(f"seeded unit {u.index}", unit_text(u)) for u in plan.seeded_units]
    for i, (label, text) in enumerate(streamed):
        if not text:
            raise ValueError(f"rung {plan.rung}: {label} is empty")
        for other_label, other in streamed[i + 1 :] + seeded:
            if text.startswith(other) or other.startswith(text):
                fail("share a prefix", label, other_label)


def plan_rung(
    corpus: Corpus,
    rung: str,
    chars_per_token: float = PROVISIONAL_CHARS_PER_TOKEN,
    stream_tail_chars: Optional[int] = None,
    dollars: bool = False,
) -> RungPlan:
    """Which units are SEEDED and which one STREAMS.

    Only the last reply streams. At the field's own cadence, 24 characters every 73ms, a million
    tokens is three and a half hours of streaming; a benchmark nobody can run measures nothing.
    The seeded/streamed equivalence is CHECKED at the 10K rung rather than assumed, and rungs
    above it are labelled `fidelity: seeded_only` when that check fails.
    """
    tokens = RUNGS[rung]
    target_chars = int(tokens * chars_per_token)

    # THE STREAMED TAIL IS THE SAME SIZE AT EVERY RUNG, and the whole size ladder lives in the
    # seeded prefix. This is not tidiness, it is what makes the film mean anything above 10K.
    #
    # The scene is a FIXED-DURATION film whose slots are wall-clock times: three actions run
    # "during generation" and ten run "after the reply is complete". At the field's own cadence
    # of 24 characters every 73 ms, a streamed tail that grows with the rung takes 11 s at 1K,
    # 54 s at 10K, 354 s at 100K and 811 s at 1M -- against a film 135 s long. Above 10K the
    # stream outlasts the entire film, so every action labelled "after the reply is complete"
    # runs mid-generation. The run still completes and still prints a full table; the labels are
    # simply false, which is worse than a crash.
    #
    # Holding the tail constant also isolates the variable under investigation. The question is
    # what a streamed chunk costs AS A FUNCTION OF THE THREAD ALREADY ON SCREEN, and that needs
    # the chunk workload held fixed while the thread grows, not both moving together.
    # `stream_tail_chars` overrides the constant, and is the ONLY way to vary reply length in this
    # tool. The paragraphs above explain why the tail is pinned: the rung ladder exists to ask what
    # a chunk costs as a function of the THREAD, and that needs the chunk workload held fixed. The
    # consequence, which cost a whole investigation to rediscover, is that a cost scaling with the
    # length of the reply BEING STREAMED is constant across every rung and reads as a floor. Such a
    # mechanism is real and this ladder cannot see it at any effect size.
    #
    # Raising this makes the film's labels false in the way the note above describes, because the
    # stream then outlasts the after-generation slots. That is a trade a reply-length investigation
    # has to make deliberately, so it is a parameter and not a second constant, and `--assert-
    # liveness` on the resulting payload is how the cost of making it shows up.
    turns = STREAM_TURNS if target_chars >= MULTI_TURN_MIN_CHARS else 1
    tail_budget = STREAM_TAIL_CHARS if stream_tail_chars is None else max(1, stream_tail_chars)
    tail_target = min(tail_budget, target_chars) if stream_tail_chars is None else tail_budget
    follow_budget = FOLLOW_UP_CHARS * (turns - 1)
    seed_target = max(0, target_chars - tail_target - follow_budget)

    # Size the SEEDED PREFIX to the remainder, then trim its last unit to land on the target.
    # Growing it a whole unit at a time instead overshoots by up to one turn, which at the 1K
    # rung means 13,333 characters against a 4,000-character budget.
    last_index = max(e["index"] for e in corpus.manifest["units"])
    try:
        seeded = corpus.units_for_chars(seed_target) if seed_target > 0 else []
    except KeyError as exc:
        # The prefix alone outgrew the manifest, before any streamed turn was even asked for.
        raise _too_small(rung, chars_per_token, last_index, "its seeded prefix alone") from exc
    if seeded:
        overshoot = sum(u.chars for u in seeded) - seed_target
        if overshoot > 0:
            seeded[-1] = seeded[-1].clipped_to(max(1, seeded[-1].chars - overshoot))

    # The streamed turn is the next one after the prefix, clipped to the fixed tail, and each
    # follow-up is the one after that.
    #
    # NO CLAMP HERE, deliberately. This used to be `min(index, last_index)`, so a rung whose prefix
    # reached the end of the manifest silently got the final unit three times over: the opening
    # stream re-sent text the seeded prefix already held, both follow-ups were byte-identical, and
    # every fence in all three hit Shiki's source-keyed cache. Running off the end is a corpus that
    # is too small for the ladder, and the only honest answer is to say so and stop. `--freeze`
    # sizes the manifest from the ladder (`manifest_unit_count`) precisely so this cannot be
    # reached by any supported configuration.
    needed = len(seeded) + turns - 1
    if needed > last_index:
        raise _too_small(
            rung,
            chars_per_token,
            last_index,
            f"its {len(seeded)}-unit seeded prefix plus {turns} streamed turns need units up to "
            f"index {needed}, which",
        )

    # The streaming budget is SPLIT across the opening turn and the follow-ups, so a cell that
    # streams three times takes the same wall clock as one that streams once. Turns are taken from
    # consecutive corpus units, which alternate reasoning-heavy and code-heavy, so the follow-ups
    # exercise the `<think>` re-parse and the Streamdown path rather than repeating one of them.
    # The opening turn keeps the FULL tail budget and the follow-ups are extra. The three
    # during-generation slots are timed against the opening stream, so it has to outlast them;
    # splitting the budget between turns left it draining in four seconds and those slots then ran
    # against a finished reply while still being labelled "during generation".
    source = corpus.unit(len(seeded))
    # THE REQUESTED TAIL HAS TO BE DELIVERABLE. Keyed on `clipped_to`'s own early return
    # (`if chars >= self.chars: return self`) rather than on a tolerance, because the two ways a
    # tail lands under its budget are different in kind and only one of them is a defect: clipping
    # at a whole BLOCK boundary loses at most one block and is what keeps a prefix from ending
    # inside a fence, while exceeding the unit loses everything above it and is unbounded. A
    # percentage bound cannot tell those apart, and a bound nobody can derive is an unacknowledged
    # bias rather than a tolerance.
    #
    # The DEFAULT path is exempt on purpose: `STREAM_TAIL_CHARS` is a ceiling the small rungs are
    # legitimately under (the 1K rung is 4,000 characters in total, less than one tail), and that
    # shortfall is the rung being small rather than the corpus failing to answer.
    if stream_tail_chars is not None and tail_target >= source.chars:
        raise _tail_not_deliverable(
            rung,
            tail_target,
            len(seeded),
            source.chars,
            sum(u.chars for u in seeded) + source.chars + FOLLOW_UP_CHARS * (turns - 1),
            target_chars,
        )
    streamed = source.clipped_to(tail_target)
    follow_ups = [corpus.unit(len(seeded) + i).clipped_to(FOLLOW_UP_CHARS) for i in range(1, turns)]
    if dollars:
        # The streamed turns only. The seeded prefix is rendered once at mount and never
        # re-preprocessed, so dollars there would change the corpus without changing what the
        # per-frame path is asked to do.
        streamed = replace(
            streamed,
            reasoning = dollarise(streamed.reasoning, "r"),
            content = dollarise(streamed.content, "c"),
        )
        streamed = replace(streamed, chars = len(streamed.reasoning) + len(streamed.content))
        follow_ups = [
            replace(u, reasoning = dollarise(u.reasoning, "r"), content = dollarise(u.content, "c"))
            for u in follow_ups
        ]
        follow_ups = [replace(u, chars = len(u.reasoning) + len(u.content)) for u in follow_ups]

    plan = RungPlan(
        rung = rung,
        target_tokens = tokens,
        target_chars = target_chars,
        seeded_units = seeded,
        streamed_unit = streamed,
        follow_up_units = follow_ups,
    )
    check_streamed_units_are_new(plan)
    return plan


def _main(argv: list[str]) -> int:
    import argparse

    ap = argparse.ArgumentParser(description = "Build or verify the frozen studiobench corpus.")
    ap.add_argument("--freeze", action = "store_true", help = "regenerate frozen/*.jsonl")
    ap.add_argument("--verify", action = "store_true", help = "check the tree against the freeze")
    args = ap.parse_args(argv)
    if args.freeze:
        m = freeze()
        print(
            f"froze {m['shipped_units']} units, {m['shipped_chars']:,} chars, "
            f"{len(m['units'])} manifest entries"
        )
        print(f"corpus_hash {m['corpus_hash']}")
        return 0
    c = Corpus.load()
    n = 0
    for _ in c.iter_units():
        n += 1
    print(f"verified {n} units against corpus_hash {c.corpus_hash}")
    print(f"regenerated (not shipped as text): {len(c.regenerated)} units")
    for rung in RUNGS:
        p = plan_rung(c, rung)
        print(
            f"  {rung:>5}: {len(p.seeded_units):>4} seeded units, "
            f"{p.seeded_chars:>10,} seeded chars, {p.streamed_chars:>9,} streamed chars"
        )
    return 0


if __name__ == "__main__":
    import sys
    raise SystemExit(_main(sys.argv[1:]))
