# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

"""The model families the pinned audio.cpp runtime loads, for prebuilt bundles that ship no ``model_specs/``.

A family Studio does not list is offered from the tasks its GGUF's spec declares, and that spec can
be newer than the runtime. This set lets Studio refuse such a family up front instead of failing at
load with "unsupported model family hint". It holds only for the tag it was generated from.
"""

from __future__ import annotations

AUDIO_CPP_SPEC_FAMILIES_TAG = "v0.9.0-unsloth.1"

# Regenerate on a pin bump: the stems of model_specs/*.json in unslothai/audio.cpp at that tag.
AUDIO_CPP_SPEC_FAMILIES = frozenset(
    (
        "ace_step",
        "apollo",
        "audio8_asr",
        "audio8_tts",
        "audiosr",
        "auk",
        "breeze_tts",
        "bs_roformer",
        "builtin_audio_utils",
        "canary_asr",
        "chatterbox",
        "chatterbox_turbo",
        "citrinet_asr",
        "cohere_asr",
        "confucius4_r2t2",
        "confucius4_tts",
        "controlfoley",
        "cosyvoice3",
        "dots_tts",
        "dramabox",
        "echo_tts",
        "f5_tts",
        "firered_audio",
        "fireredtts3",
        "fish_audio",
        "fun_asr_nano",
        "gigaam_asr",
        "glm_tts",
        "granite5asr",
        "heartmula",
        "higgs_audio_stt",
        "higgs_audio_tts",
        "htdemucs",
        "htdemucs_6stems",
        "hviske_asr",
        "index_tts2",
        "inflect_v2",
        "irodori_tts",
        "kitten_tts",
        "kokoro_tts",
        "kroko_asr",
        "liveavatar",
        "magpie_tts",
        "maya1",
        "meanvc2",
        "mel_band_roformer",
        "midashenglm_gen",
        "minimax_h3",
        "minimax_music3",
        "miocodec",
        "miotts",
        "mira_tts",
        "mms_forced_aligner",
        "moonshine_asr",
        "moss_transcribe_diarize",
        "moss_tts_local",
        "moss_tts_nano",
        "moss_tts_v15",
        "moss_ttsd",
        "moss_voicegen",
        "muscriptor",
        "nemotron_3_diar",
        "nemotron_asr",
        "neutts",
        "niagara_asr",
        "omnivoice",
        "outetts",
        "parakeet_tdt",
        "personaplex",
        "piper_tts",
        "pocket_tts",
        "pulsevad",
        "qwen3_asr",
        "qwen3_forced_aligner",
        "qwen3_tts",
        "rvc",
        "sam_audio",
        "samsone",
        "sanotts",
        "seed_vc",
        "sense_asr",
        "sheetsage2",
        "soprano_tts",
        "sopro_tts",
        "sortformer_diar",
        "sortformer_diar_v2",
        "stable_audio",
        "supertonic",
        "tone_color_vc",
        "universr",
        "vevo2",
        "vibeasr",
        "vibevoice",
        "vibevoice_asr",
        "vibevoice_asr_streaming",
        "vieneu_v3_turbo",
        "voxcpm1",
        "voxcpm2",
        "voxtral_realtime",
        "yue2",
        "zipvoice",
    )
)
