# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved.

"""An upstream install-cell fix has to reach the container.

`middle_digest` counted the whole generated install cell as boilerplate. Only half
true: its comments and spacing churn every upstream build, but the package specs do
not, and a pin bump lives entirely in that cell. SAME does not merely skip the copy,
it re-records the OLD hash, so such a notebook never converges.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SIG_PATH = REPO_ROOT / "docker" / "unsloth_nb_content_sig.py"

_INSTALL = "!pip install --upgrade unsloth transformers==4.56.2\n"


@pytest.fixture(scope = "module")
def sig():
    assert SIG_PATH.is_file(), f"missing {SIG_PATH}"
    spec = importlib.util.spec_from_file_location("unsloth_nb_content_sig_t", SIG_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _write(path: Path, *sources) -> Path:
    cells = []
    for cell_type, text in sources:
        cells.append({"cell_type": cell_type, "source": [text], "metadata": {}})
    path.write_text(
        json.dumps({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}),
        encoding = "utf-8",
    )
    return path


def _same(sig, tmp_path: Path, before, after) -> bool:
    a = _write(tmp_path / "a.ipynb", *before)
    b = _write(tmp_path / "b.ipynb", *after)
    return sig.middle_digest(str(a)) == sig.middle_digest(str(b))


def test_a_pin_bump_in_the_install_cell_is_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", _INSTALL.replace("4.56.2", "5.5.0")), ("code", "print(1)\n")],
    ), "a changed version pin must make the notebook refresh"


def test_an_added_dependency_is_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", _INSTALL.rstrip("\n") + " trl\n"), ("code", "print(1)\n")],
    ), "an added package must make the notebook refresh"


def test_a_removed_install_cell_is_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "!pip install extras\n"), ("code", "print(1)\n")],
        [("code", _INSTALL), ("code", "print(1)\n")],
    ), "dropping an install cell must make the notebook refresh"


def test_cosmetic_install_churn_is_still_the_same(sig, tmp_path: Path):
    # why the cell was skipped at all: upstream regenerates it every build
    churned = (
        "# regenerated by update_all_notebooks.py\n"
        "\n"
        "!pip install    --upgrade   unsloth   transformers==4.56.2\n"
        "   # keep the pin in step with the sidecar\n"
    )
    assert _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", churned), ("code", "print(1)\n")],
    ), "comment/whitespace churn in the install cell must not force a refresh"


def test_a_url_fragment_is_not_mistaken_for_a_comment(sig, tmp_path: Path):
    # `#subdirectory=` selects the package, so stripping it hashes two installs alike
    a = '!pip install "git+https://github.com/o/r#subdirectory=pkg_a"\n'
    b = '!pip install "git+https://github.com/o/r#subdirectory=pkg_b"\n'
    assert not _same(
        sig, tmp_path, [("code", a), ("code", "print(1)\n")], [("code", b), ("code", "print(1)\n")]
    ), "a #fragment inside a requirement is data, not a comment"


def test_boilerplate_markdown_is_still_ignored(sig, tmp_path: Path):
    assert _same(
        sig,
        tmp_path,
        [("markdown", "To run this, press Runtime\n"), ("code", "print(1)\n")],
        [("markdown", "To run this, press Runtime and Run all\n"), ("code", "print(1)\n")],
    ), "the announcement block must still be excluded"


def test_a_body_change_is_still_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", _INSTALL), ("code", "print(2)\n")],
    ), "a real code change must still make the notebook refresh"


# `" ".join(line.split())` drops the LEADING whitespace too, but upstream's cell is an
# `if "COLAB_" not in ...: / else:` block and the image is always the non-Colab branch,
# so moving a line out of the `else:` body is functional, not churn.

_UPSTREAM_HEAD = (
    "%%capture\n"
    "import os, re\n"
    'if "COLAB_" not in "".join(os.environ.keys()):\n'
    "    !pip install unsloth\n"
    "else:\n"
    '    !pip install sentencepiece protobuf "datasets==4.3.0" hf_transfer\n'
    "    !pip install --no-deps unsloth_zoo bitsandbytes accelerate peft trl triton unsloth\n"
)


def test_moving_an_install_line_out_of_the_colab_branch_is_visible(sig, tmp_path: Path):
    # same lines, same order, one dedent: Colab-only becomes every runtime
    inside = _UPSTREAM_HEAD + '    !pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    outside = _UPSTREAM_HEAD + '!pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    assert not _same(
        sig,
        tmp_path,
        [("code", inside), ("code", "print(1)\n")],
        [("code", outside), ("code", "print(1)\n")],
    ), "dedenting an install line out of the Colab-only branch must force a refresh"


def test_indenting_an_install_line_into_the_colab_branch_is_visible(sig, tmp_path: Path):
    outside = _UPSTREAM_HEAD + '!pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    inside = _UPSTREAM_HEAD + '    !pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    assert not _same(
        sig,
        tmp_path,
        [("code", outside), ("code", "print(1)\n")],
        [("code", inside), ("code", "print(1)\n")],
    ), "indenting an install line into the Colab-only branch must force a refresh"


def test_indentation_churn_inside_the_cell_is_still_cosmetic(sig, tmp_path: Path):
    churned = (
        "%%capture\n"
        "# regenerated by update_all_notebooks.py\n"
        "import os,   re\n"
        "\n"
        'if "COLAB_" not in "".join(os.environ.keys()):\n'
        "\t!pip install    unsloth\n"
        "    # keep the pin in step with the sidecar\n"
        "else:\n"
        '\t!pip install sentencepiece protobuf "datasets==4.3.0"  hf_transfer\n'
        "\t!pip install  --no-deps unsloth_zoo bitsandbytes accelerate peft trl triton unsloth\n"
    )
    assert _same(
        sig,
        tmp_path,
        [("code", _UPSTREAM_HEAD), ("code", "print(1)\n")],
        [("code", churned), ("code", "print(1)\n")],
    ), "comment/blank/inner-spacing/tab churn at the same depth must stay SAME"
