# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved.

"""An upstream install-cell fix has to reach the container.

`unsloth_nb_content_sig.middle_digest` decides, for the boot refresh in
`unsloth_sync_notebooks.sh`, whether an upstream notebook differs from the one
already on disk. It skipped boilerplate so a regenerated announcement or footer
would not rewrite every notebook on every boot -- and it counted the whole
generated install cell as boilerplate.

That is only half true. The comments, blank lines and spacing in that cell do
churn on every upstream build, but its package specifications do not: when
upstream fixes `unsloth/gemma-4-E2B-it is not supported yet in
transformers==4.56.2` by bumping the pin, the fix lives entirely in that cell.
With the cell excluded the digest reported SAME, and SAME does not merely skip
the copy -- it re-records the OLD hash, so the notebook never converges and the
user keeps a broken install forever. The image also derives its transformers
sidecar from that pin (`unsloth_pip_shim.py`), so the wrong sidecar stays
selected too.

So the cell is hashed, with only the cosmetics normalized away. No docker, no
network.
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SIG_PATH = REPO_ROOT / "docker" / "unsloth_nb_content_sig.py"

_INSTALL = "!pip install --upgrade unsloth transformers==4.56.2\n"


@pytest.fixture(scope = "module")
def sig():
    assert SIG_PATH.is_file(), f"missing {SIG_PATH}"
    spec = importlib.util.spec_from_file_location("unsloth_nb_content_sig_t", SIG_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _write(path: Path, *sources) -> Path:
    cells = []
    for cell_type, text in sources:
        cells.append({"cell_type": cell_type, "source": [text], "metadata": {}})
    path.write_text(
        json.dumps({"cells": cells, "metadata": {}, "nbformat": 4, "nbformat_minor": 5}),
        encoding = "utf-8",
    )
    return path


def _same(sig, tmp_path: Path, before, after) -> bool:
    a = _write(tmp_path / "a.ipynb", *before)
    b = _write(tmp_path / "b.ipynb", *after)
    return sig.middle_digest(str(a)) == sig.middle_digest(str(b))


def test_a_pin_bump_in_the_install_cell_is_visible(sig, tmp_path: Path):
    # The reported case: upstream fixes a model that needs a newer transformers
    # by editing only this cell.
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", _INSTALL.replace("4.56.2", "5.5.0")), ("code", "print(1)\n")],
    ), "a changed version pin must make the notebook refresh"


def test_an_added_dependency_is_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", _INSTALL.rstrip("\n") + " trl\n"), ("code", "print(1)\n")],
    ), "an added package must make the notebook refresh"


def test_a_removed_install_cell_is_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "!pip install extras\n"), ("code", "print(1)\n")],
        [("code", _INSTALL), ("code", "print(1)\n")],
    ), "dropping an install cell must make the notebook refresh"


def test_cosmetic_install_churn_is_still_the_same(sig, tmp_path: Path):
    # The reason the cell was skipped in the first place: upstream regenerates
    # it every build. Comments, blank lines and spacing must not rewrite ~430
    # notebooks on every boot.
    churned = (
        "# regenerated by update_all_notebooks.py\n"
        "\n"
        "!pip install    --upgrade   unsloth   transformers==4.56.2\n"
        "   # keep the pin in step with the sidecar\n"
    )
    assert _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", churned), ("code", "print(1)\n")],
    ), "comment/whitespace churn in the install cell must not force a refresh"


def test_a_url_fragment_is_not_mistaken_for_a_comment(sig, tmp_path: Path):
    # `#subdirectory=` selects the package; stripping it as a comment would make
    # two different installs hash the same.
    a = '!pip install "git+https://github.com/o/r#subdirectory=pkg_a"\n'
    b = '!pip install "git+https://github.com/o/r#subdirectory=pkg_b"\n'
    assert not _same(
        sig, tmp_path, [("code", a), ("code", "print(1)\n")], [("code", b), ("code", "print(1)\n")]
    ), "a #fragment inside a requirement is data, not a comment"


def test_boilerplate_markdown_is_still_ignored(sig, tmp_path: Path):
    assert _same(
        sig,
        tmp_path,
        [("markdown", "To run this, press Runtime\n"), ("code", "print(1)\n")],
        [("markdown", "To run this, press Runtime and Run all\n"), ("code", "print(1)\n")],
    ), "the announcement block must still be excluded"


def test_a_body_change_is_still_visible(sig, tmp_path: Path):
    assert not _same(
        sig,
        tmp_path,
        [("code", _INSTALL), ("code", "print(1)\n")],
        [("code", _INSTALL), ("code", "print(2)\n")],
    ), "a real code change must still make the notebook refresh"


# --- indentation is not cosmetic --------------------------------------------
# `_normalize_install` collapsed each line with `" ".join(line.split())`, which
# drops the LEADING whitespace too. Upstream's generated cell is an
# `if "COLAB_" not in "".join(os.environ.keys()): / else:` block (see
# unslothai/notebooks update_all_notebooks.py `installation_content`), so a
# line's indent decides which runtime its `!pip install` runs on -- and the
# Docker image is always the non-Colab branch. Moving one line out of the
# `else:` body is a functional change that hashed identically, and SAME does not
# just skip the copy, it re-records the OLD hash, so the notebook never
# converges.

_UPSTREAM_HEAD = (
    "%%capture\n"
    "import os, re\n"
    'if "COLAB_" not in "".join(os.environ.keys()):\n'
    "    !pip install unsloth\n"
    "else:\n"
    '    !pip install sentencepiece protobuf "datasets==4.3.0" hf_transfer\n'
    "    !pip install --no-deps unsloth_zoo bitsandbytes accelerate peft trl triton unsloth\n"
)


def test_moving_an_install_line_out_of_the_colab_branch_is_visible(sig, tmp_path: Path):
    # Same lines, same order, one dedent: `torchao` goes from Colab-only to
    # every runtime. Both variants are valid Python.
    inside = _UPSTREAM_HEAD + '    !pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    outside = _UPSTREAM_HEAD + '!pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    assert not _same(
        sig,
        tmp_path,
        [("code", inside), ("code", "print(1)\n")],
        [("code", outside), ("code", "print(1)\n")],
    ), "dedenting an install line out of the Colab-only branch must force a refresh"


def test_indenting_an_install_line_into_the_colab_branch_is_visible(sig, tmp_path: Path):
    # The other direction: a package that used to install everywhere becomes
    # Colab-only, i.e. the Docker image silently stops getting it.
    outside = _UPSTREAM_HEAD + '!pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    inside = _UPSTREAM_HEAD + '    !pip install --no-deps --upgrade "torchao>=0.16.0"\n'
    assert not _same(
        sig,
        tmp_path,
        [("code", outside), ("code", "print(1)\n")],
        [("code", inside), ("code", "print(1)\n")],
    ), "indenting an install line into the Colab-only branch must force a refresh"


def test_indentation_churn_inside_the_cell_is_still_cosmetic(sig, tmp_path: Path):
    # Preserving the indent must not resurrect the churn the normalizer exists
    # for: comments, blank lines, inner spacing and a tab/space rewrite of the
    # SAME structure all still have to read as unchanged.
    churned = (
        "%%capture\n"
        "# regenerated by update_all_notebooks.py\n"
        "import os,   re\n"
        "\n"
        'if "COLAB_" not in "".join(os.environ.keys()):\n'
        "\t!pip install    unsloth\n"
        "    # keep the pin in step with the sidecar\n"
        "else:\n"
        '\t!pip install sentencepiece protobuf "datasets==4.3.0"  hf_transfer\n'
        "\t!pip install  --no-deps unsloth_zoo bitsandbytes accelerate peft trl triton unsloth\n"
    )
    assert _same(
        sig,
        tmp_path,
        [("code", _UPSTREAM_HEAD), ("code", "print(1)\n")],
        [("code", churned), ("code", "print(1)\n")],
    ), "comment/blank/inner-spacing/tab churn at the same depth must stay SAME"
