# Copyright 2023-present Daniel Han-Chen & the Unsloth team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""``python -m unsloth.spec_decoding.cli measure`` — command-line entry point."""

from __future__ import annotations

import argparse
import sys


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog = "unsloth-spec-decode",
        description = "Measure speculative-decoding acceptance rate and expected speedup "
        "for a target/draft model pair.",
    )
    sub = p.add_subparsers(dest = "command", required = True)

    m = sub.add_parser("measure", help = "measure acceptance for a target/draft pair")
    m.add_argument("--target", required = True, help = "HF id or path of the target (large) model")
    m.add_argument("--draft", required = True, help = "HF id or path of the draft (small) model")
    m.add_argument(
        "--data",
        default = "builtin",
        help = "'builtin', a .txt path, or 'hf:<dataset>:<split>:<column>'",
    )
    m.add_argument("--max-samples", type = int, default = 32)
    m.add_argument("--max-length", type = int, default = 256)
    m.add_argument("--min-length", type = int, default = 8)
    m.add_argument(
        "--chat-template",
        action = "store_true",
        help = "wrap each text in the tokenizer's chat template",
    )

    m.add_argument("--temperature", type = float, default = 1.0, help = "0 = greedy")
    m.add_argument("--top-k", type = int, default = 0)
    m.add_argument("--top-p", type = float, default = 1.0)
    m.add_argument("--gamma", type = int, default = 4, help = "draft block size")
    m.add_argument(
        "--cost-ratio",
        type = float,
        default = 0.15,
        help = "draft-forward cost / target-forward cost, for the speedup estimate",
    )

    m.add_argument(
        "--continuation-tokens",
        type = int,
        default = 0,
        help = "score acceptance on N tokens generated by the target rather than "
        "on the prompt itself (recommended; 64-128 is typical)",
    )
    m.add_argument(
        "--simulate",
        action = "store_true",
        help = "also run the real rejection-sampling loop; the only way to get "
        "acceptance per draft offset",
    )
    m.add_argument("--simulate-max-new-tokens", type = int, default = 96)
    m.add_argument("--seed", type = int, default = 0)

    m.add_argument("--device", default = None, help = "cuda | mps | cpu (auto by default)")
    m.add_argument("--dtype", default = None, help = "float32 | float16 | bfloat16")
    m.add_argument(
        "--use-unsloth",
        action = "store_true",
        help = "load via unsloth FastLanguageModel (needs a GPU)",
    )
    m.add_argument("--json", action = "store_true", help = "emit JSON instead of a table")
    return p


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if args.command != "measure":  # pragma: no cover - argparse enforces
        return 2

    # heavy imports deferred so `--help` is instant
    import torch  # noqa: PLC0415

    from .data import build_sequences, load_texts
    from .measure import measure_acceptance
    from .models import check_vocab_compatible, load_model_and_tokenizer
    from .report import to_json, to_text
    from .sampling import SamplingParams

    sampling = SamplingParams(temperature = args.temperature, top_k = args.top_k, top_p = args.top_p)

    print(f"loading target: {args.target}", file = sys.stderr)
    target_model, target_tok, device = load_model_and_tokenizer(
        args.target, device = args.device, dtype = args.dtype, use_unsloth = args.use_unsloth
    )
    print(f"loading draft:  {args.draft}", file = sys.stderr)
    draft_model, draft_tok, _ = load_model_and_tokenizer(
        args.draft, device = device, dtype = args.dtype, use_unsloth = args.use_unsloth
    )
    check_vocab_compatible(target_tok, draft_tok)

    texts = load_texts(args.data)
    sequences = build_sequences(
        texts,
        target_tok,
        max_samples = args.max_samples,
        max_length = args.max_length,
        min_length = args.min_length,
        chat_template = args.chat_template,
    )
    print(f"scoring {len(sequences)} sequences on {device}", file = sys.stderr)

    eos = getattr(target_tok, "eos_token_id", None)
    with torch.no_grad():
        report = measure_acceptance(
            target_model,
            draft_model,
            sequences,
            sampling = sampling,
            gamma = args.gamma,
            cost_ratio = args.cost_ratio,
            device = device,
            continuation_tokens = args.continuation_tokens,
            simulate = args.simulate,
            simulate_max_new_tokens = args.simulate_max_new_tokens,
            seed = args.seed,
            eos_token_id = eos,
        )

    print(to_json(report) if args.json else to_text(report, args.target, args.draft))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
