# SPDX-License-Identifier: AGPL-3.0-only
# Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

"""Build `dist/studiobench.pyz`: ONE file an external tester runs.

    python -m tests.studio.studiobench.build
    python dist/studiobench.pyz --doctor

WHY ONE FILE. The people whose machines matter most are the ones who will not clone a monorepo,
create a virtualenv and read a README to find out that their laptop drops frames at 90K characters.
A zipapp is `python studiobench.pyz --doctor`, and the doctor then says in one screen what is
missing and what each missing piece costs.

WHAT GOES IN. The package, the frozen corpus, and the pieces of `tests/studio/_playwright_robust.py`
that the runtime asks for by name. What does NOT go in is anything from `pip`: a zipapp cannot
carry Playwright, which ships a node driver and a browser, so the bootstrap is stdlib-only and
`--doctor` is what tells a tester to `pip install playwright && playwright install`.

WHAT IS DELIBERATELY NOT COMPRESSED AWAY. `fixture/corpus/frozen/units.jsonl` is most of the
artifact's size and all of its meaning: it is the frozen text, and shipping the generator instead
of the text would make every tester's corpus a function of their own copy of the generator. The
manifest's per-unit digests are checked at load, so a corpus that drifted refuses to run rather
than quietly measuring something else.
"""

from __future__ import annotations

import shutil
import zipapp
from pathlib import Path

PKG = Path(__file__).resolve().parent
REPO = PKG.parents[2]
DEFAULT_OUT = REPO / "dist" / "studiobench.pyz"

# Everything under the package except caches and the build's own scratch.
EXCLUDE_DIRS = {"__pycache__", ".pytest_cache", "dist", "build"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo"}

MAIN = "tests.studio.studiobench.__main__:main_argv"


def _copy_package(staging: Path) -> None:
    target = staging / "tests" / "studio" / "studiobench"
    target.parent.mkdir(parents = True, exist_ok = True)
    shutil.copytree(PKG, target, ignore = shutil.ignore_patterns(*EXCLUDE_DIRS, "*.pyc", "*.pyo"))
    # `tests` and `tests/studio` must be importable packages inside the archive, and they are not
    # packages in the repository: the harnesses there are standalone scripts.
    for pkg_dir in (staging / "tests", staging / "tests" / "studio"):
        init = pkg_dir / "__init__.py"
        if not init.exists():
            init.write_text("# generated by studiobench.build\n", encoding = "utf-8")


def _copy_robust(staging: Path) -> bool:
    """`_playwright_robust.py` if it is there.

    Vendored rather than imported, for the same reason lifecycle is: the artifact runs on a
    machine with no checkout. `runtime/browser.py` imports it by either name and survives its
    absence, so a build without it is degraded rather than broken -- it loses the maintained
    Chromium flags, the view-transition killer and `dump_diagnostics`.
    """
    src = REPO / "tests" / "studio" / "_playwright_robust.py"
    if not src.exists():
        return False
    shutil.copy2(src, staging / "tests" / "studio" / "_playwright_robust.py")
    return True


def build(out: Path = DEFAULT_OUT, compressed: bool = True) -> Path:
    out = Path(out).resolve()
    out.parent.mkdir(parents = True, exist_ok = True)
    staging = out.parent / "_studiobench_staging"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir(parents = True)

    _copy_package(staging)
    had_robust = _copy_robust(staging)

    frozen = staging / "tests" / "studio" / "studiobench" / "fixture" / "corpus" / "frozen"
    if not (frozen / "manifest.json").exists():
        raise FileNotFoundError(
            "the frozen corpus is not in the tree. Run "
            "`python -m tests.studio.studiobench.fixture.corpus --freeze` before building, or the "
            "artifact ships a benchmark with no content."
        )

    # A __main__.py at the archive root is what `python foo.pyz` executes. It re-exports the package's
    # CLI rather than duplicating it.
    (staging / "__main__.py").write_text(
        "import sys\n"
        "from tests.studio.studiobench.__main__ import main\n"
        "raise SystemExit(main(sys.argv[1:]))\n",
        encoding = "utf-8",
    )

    zipapp.create_archive(
        staging, target = out, interpreter = "/usr/bin/env python3", compressed = compressed
    )
    shutil.rmtree(staging)
    size_mb = out.stat().st_size / 1048576
    print(f"built {out} ({size_mb:.1f} MB)")
    if not had_robust:
        print(
            "  NOTE: _playwright_robust.py was not found, so the artifact falls back to its own "
            "Chromium flags and diagnostics"
        )
    print(f"  run it with: python {out.name} --doctor")
    return out


def _main(argv: list) -> int:
    import argparse

    ap = argparse.ArgumentParser(description = "Build the studiobench zipapp.")
    ap.add_argument("--out", default = str(DEFAULT_OUT))
    ap.add_argument("--no-compress", action = "store_true")
    args = ap.parse_args(argv)
    build(Path(args.out), compressed = not args.no_compress)
    return 0


if __name__ == "__main__":
    import sys
    raise SystemExit(_main(sys.argv[1:]))
