// SPDX-License-Identifier: AGPL-3.0-only
// Copyright 2026-present the Unsloth AI Inc. team. All rights reserved. See /studio/LICENSE.AGPL-3.0

import type { TranslationKey } from "@/i18n";
import type { SettingsTab } from "./stores/settings-dialog-store";

/**
 * Searchable entries per tab: the label/title keys rendered by each tab.
 * Tab names themselves always match, so tabs without translatable rows
 * (profile, connections) are still reachable from search.
 */
export const SETTINGS_SEARCH_INDEX: Record<SettingsTab, TranslationKey[]> = {
  general: [
    "settings.general.account",
    "settings.general.password",
    "settings.general.huggingFaceToken",
    "settings.general.gettingStarted",
    "settings.general.startOnboarding",
    "settings.general.storage.sectionTitle",
    "settings.general.storage.modelsFolder",
    "settings.appearance.language.title",
    "settings.appearance.language.label",
    "settings.general.notifications.sectionTitle",
    "settings.general.notifications.showLlamaUpdates",
    "settings.general.previewSharing.sectionTitle",
    "settings.general.previewSharing.enableLabel",
    "settings.general.previewSharing.revokeLabel",
    "settings.general.rag.sectionTitle",
    "settings.general.rag.embeddingModel",
    "settings.general.helperLlm.sectionTitle",
    "settings.general.helperLlm.preloadOnStartup",
    "settings.general.uploads.sectionTitle",
    "settings.general.uploads.maxUploadSize",
    "settings.general.resetPreferences.sectionTitle",
    "settings.general.resetPreferences.label",
  ],
  profile: [
    "settings.profile.title",
    "settings.profile.description",
    "settings.profile.displayName",
    "settings.profile.nickname",
    "settings.profile.avatarShape",
    "settings.profile.greetingSloth",
  ],
  appearance: [
    "settings.appearance.theme.label",
    "settings.appearance.palette.label",
    "settings.appearance.custom.colors.accent",
    "settings.appearance.custom.colors.background",
    "settings.appearance.custom.colors.foreground",
    "settings.appearance.custom.uiFont.label",
    "settings.appearance.custom.headingFont.label",
    "settings.appearance.custom.chatFont.label",
    "settings.appearance.custom.codeFont.label",
    "settings.appearance.custom.contrast.label",
    "settings.appearance.custom.pointerCursors.label",
    "settings.appearance.custom.reduceMotion.label",
    "settings.appearance.custom.uiFontSize.label",
    "settings.appearance.custom.codeFontSize.label",
    "settings.appearance.custom.fontSmoothing.label",
    "settings.appearance.layout.compactSidebar",
    "settings.appearance.sidebarMenu.title",
    "settings.appearance.sidebarMenu.darkModeToggle",
  ],
  resources: [
    "settings.resources.liveMonitor.title",
    "settings.resources.liveMonitor.cpu",
    "settings.resources.liveMonitor.ram",
    "settings.resources.liveMonitor.vram",
    "settings.resources.liveMonitor.disk",
    "settings.resources.gpu.title",
    "settings.resources.storage.title",
    "settings.resources.storage.modelsFolder",
    "settings.resources.storage.systemDisk",
    "settings.resources.environment.title",
    "settings.resources.environment.backend",
    "settings.resources.environment.python",
    "settings.resources.environment.torch",
    "settings.resources.environment.transformers",
    "settings.resources.liveUpdates",
  ],
  chat: [
    "settings.general.chatDefaults",
    "settings.general.autoTitleNewChats",
    "settings.chat.artifacts.title",
    "settings.chat.artifacts.collapseHtmlBlocks",
    "settings.chat.artifacts.allowNetworkAccess",
    "settings.chat.data",
    "settings.chat.exportConversations",
    "settings.chat.importChats",
    "settings.chat.clearAllChats",
    "settings.chat.exportHistory",
    "settings.chat.modelDisclaimer",
  ],
  "api-keys": [
    "settings.apiKeys.title",
    "settings.apiKeys.description",
    "settings.apiKeys.accessTokens",
  ],
  connections: [],
  voice: [
    "settings.voice.dictation.sectionTitle",
    "settings.voice.dictation.microphoneLabel",
    "settings.voice.dictation.languageLabel",
    "settings.voice.dictionary.sectionTitle",
    "settings.voice.recents.sectionTitle",
    "settings.voice.readAloud.sectionTitle",
    "settings.voice.readAloud.buttonLabel",
    "settings.voice.readAloud.engineLabel",
    "settings.voice.readAloud.voiceLabel",
    "settings.voice.readAloud.speedLabel",
    "settings.voice.readAloud.pitchLabel",
    "settings.voice.readAloud.volumeLabel",
    "settings.voice.readAloud.previewLabel",
  ],
  about: [
    "settings.about.updates",
    "settings.about.releaseNotes",
    "settings.about.documentation",
    "settings.about.help",
    "settings.about.feedback",
    "settings.about.hardware",
    "settings.about.license.sectionTitle",
    "settings.about.dangerZone",
    "settings.about.shutDownStudio",
  ],
};
