#!/usr/bin/env bash
# Regression test: converting a nested portable install back to a normal one must
# also retire the portable launcher, and put it back if the conversion fails.
#
# `install.sh --portable` writes a wrapper at <master>/bin/unsloth and its closing
# summary prints that exact path as the launch command; portable mode appends
# nothing to the login PATH, so it is the only launch instruction the user ever
# got. A normal reinstall of the same tree writes its own shim under <studio>/bin
# instead, so the wrapper survived the conversion -- still exporting UNSLOTH_HOME,
# UNSLOTH_PORTABLE=1 and the cache roots before exec'ing the venv the reinstall had
# just rebuilt at the same path. The marker was gone and the tree read as normal,
# yet the documented command put the HF caches and the projects root straight back.
#
# The wrapper is moved aside rather than deleted so it rolls back with the marker:
# a failed conversion restores the portable install, and the launcher that install
# advertised has to work again. Only OUR wrapper for THIS install is touched.
#
# The fixtures are generated by install.sh's own shim block, so a change to the
# generated wrapper that the ownership test stops recognizing fails here.
set -u
HERE="$(CDPATH= cd -P -- "$(dirname "$0")" && pwd -P)"
ROOT="$HERE/../.."
INSTALL="$ROOT/install.sh"
fails=0
check() { # name expected actual
    if [ "$2" = "$3" ]; then printf '  PASS  %s\n' "$1"
    else printf '  FAIL  %s : expected [%s] got [%s]\n' "$1" "$2" "$3"; fails=$((fails+1)); fi
}

blk() { awk "$1" "$INSTALL"; }
blockA="$(blk '/^# ── Parse flags ──$/ {grab=1} grab {print} /^        _UNSLOTH_ROOT="\$HOME\/\.unsloth"$/ {seen=1} seen && /^fi$/ {exit}')"
blockB="$(blk '/^_resolve_studio_destinations\(\) \{$/ {grab=1} grab {print} grab && /^\}$/ {exit}')"
blockM="$(blk '/^_PORTABLE_MARKER_PATH_1=""$/ {grab=1} grab {print} /^_PORTABLE_SHIM_BACKUP=""$/ {exit}')"
blockD="$(blk '/^_clear_stale_portable_marker\(\) \{$/ {grab=1} grab {print} grab && /^\}$/ {exit}')"
blockR="$(blk '/^_VENV_ROLLBACK_DIR=""$/ {grab=1} grab {print} /^trap ._on_install_signal 143. TERM$/ {exit}')"
blockSHIM="$(awk '
  /^if \[ "\$_PORTABLE_MODE" = true \]; then$/ { if (!seen) grab = 1 }
  /^# why: -sfn is atomic/ { if (grab) exit }
  grab { print }
  /_shim_tmp=/ { seen = 1 }
' "$INSTALL")
fi"

# Self-validate: a refactor must fail here, not silently test "".
case "$blockA" in *"--portable) _PORTABLE_MODE=true ;;"*) : ;; *) echo "FAIL: blockA extraction broke"; exit 1 ;; esac
case "$blockB" in *'_STUDIO_HOME_REDIRECT=env'*) : ;; *) echo "FAIL: blockB extraction broke"; exit 1 ;; esac
case "$blockM" in *'_PORTABLE_SHIM_BACKUP'*) : ;; *) echo "FAIL: blockM lost the launcher slot"; exit 1 ;; esac
case "$blockM" in *'_PORTABLE_MARKER_PRIOR_2'*) : ;; *) echo "FAIL: blockM extraction broke"; exit 1 ;; esac
case "$blockD" in *'_PORTABLE_SHIM_PATH'*) : ;; *) echo "FAIL: blockD stopped recording the launcher"; exit 1 ;; esac
case "$blockD" in *'UNSLOTH_PORTABLE=1'*) : ;; *) echo "FAIL: blockD lost the ownership probe"; exit 1 ;; esac
case "$blockSHIM" in *_shim_tmp*) : ;; *) echo "FAIL: shim block extraction broke"; exit 1 ;; esac
# The restore must stay inside the rollback block: the handlers that call it are
# extracted with it here and by tests/sh/test_install_rollback_lifecycle.sh, and a
# helper defined outside that range makes every one of those snippets exit 127.
case "$blockR" in *'_restore_portable_shim() {'*) : ;; *) echo "FAIL: the launcher restore is defined outside the rollback block"; exit 1 ;; esac
case "$blockR" in *'_restore_portable_shim'*) : ;; *) echo "FAIL: nothing calls the launcher restore"; exit 1 ;; esac
case "$blockR" in *'_commit_portable_marker() {'*) : ;; *) echo "FAIL: the commit is defined outside the rollback block"; exit 1 ;; esac
# Lifted out on its own, so blockD may not call a helper defined elsewhere.
case "$blockD" in *'_restore_portable_shim'*) echo "FAIL: blockD calls the restore helper"; exit 1 ;; *) : ;; esac
# Both handlers reach the restore through _restore_portable_marker.
_exit_block="$(blk '/^_on_install_exit\(\) \{$/ {grab=1} grab {print} grab && /^\}$/ {exit}')"
_signal_block="$(blk '/^_on_install_signal\(\) \{$/ {grab=1} grab {print} grab && /^\}$/ {exit}')"
case "$_exit_block" in *'_restore_portable_marker'*) : ;; *) echo "FAIL: the EXIT handler does not restore"; exit 1 ;; esac
case "$_signal_block" in *'_restore_portable_marker'*) : ;; *) echo "FAIL: the signal handler does not restore"; exit 1 ;; esac

SNIP='set -e
C_WARN=""
substep() { printf "  . %s\n" "$1"; }
rollback_substep() { printf "  R %s\n" "$1"; }
'"$blockA"'
'"$blockB"'
_resolve_studio_destinations
UNSLOTH_ROOT="${UNSLOTH_ROOT:-}"
'"$blockM"'
'"$blockD"'
_clear_stale_portable_marker
_UNSLOTH_LOGIN_PATH="$PATH"
VENV_DIR="$STUDIO_HOME/unsloth_studio"
'"$blockR"'
# ── everything above is install.sh verbatim ──
printf "reached|%s\n" "$STUDIO_HOME"
if [ -d "$VENV_DIR" ]; then _start_studio_venv_replacement "$VENV_DIR"; fi
case "${FAIL_MODE:-fail}" in
    ok)
        _commit_studio_venv_replacement
        _commit_portable_marker
        ;;
    signal)
        kill -INT $$
        sleep 5
        ;;
    *)
        exit 7
        ;;
esac'

T="$(mktemp -d)"
trap 'rm -rf "$T"' EXIT
mkdir -p "$T/home"
new_root() { mktemp -d "$T/root.XXXXXX"; }

# A nested portable install: venv under <master>/studio, marker at <master>, and
# the launcher generated by install.sh's own shim block.
build() { # master [venv_owner_master]
    _bm="$1"; _bowner="${2:-$1}"
    mkdir -p "$_bm/studio/unsloth_studio/bin" "$_bm/bin" "$_bm/share"
    mkdir -p "$_bowner/studio/unsloth_studio/bin"
    printf '%s\n' "$_bm" > "$_bm/.unsloth-portable-root"
    # The venv entry point the wrapper execs: reports the environment it was handed.
    printf '#!/bin/sh\nprintf "%%s\\n" "${UNSLOTH_PORTABLE:-unset}"\n' \
        > "$_bowner/studio/unsloth_studio/bin/unsloth"
    chmod +x "$_bowner/studio/unsloth_studio/bin/unsloth"
    env _PORTABLE_MODE=true UNSLOTH_ROOT="$_bm" STUDIO_HOME="$_bowner/studio" \
        VENV_DIR="$_bowner/studio/unsloth_studio" _LOCAL_BIN="$_bm/bin" \
        _shim_path="$_bm/bin/unsloth" HOME="$T/home" \
        bash -c "substep(){ :; }; $blockSHIM" >/dev/null 2>&1
    [ -f "$_bm/bin/unsloth" ] || { echo "FAIL: fixture launcher was not generated"; exit 1; }
}

convert() { # studio_home [env assignments...]
    _cs="$1"; shift
    # shellcheck disable=SC2086
    env -i HOME="$T/home" PATH="$PATH" USER="${USER:-tester}" \
        UNSLOTH_STUDIO_HOME="$_cs" "$@" bash -c "$SNIP" _ > "$T/out" 2>"$T/err"
    _crc=$?
    if ! grep -q '^reached|' "$T/out"; then
        printf '  FAIL  installer snippet never reached the install (rc=%s)\n%s\n%s\n' \
            "$_crc" "$(cat "$T/out")" "$(cat "$T/err")"
        fails=$((fails + 1))
    fi
    printf '%s' "$_crc"
}

shim_state() { # master
    if [ -L "$1/bin/unsloth" ]; then printf symlink
    elif [ -f "$1/bin/unsloth" ]; then printf present
    else printf gone; fi
}
strays() { # master
    set -- "$1"/bin/.unsloth-portable-shim.*
    if [ -e "$1" ]; then printf '%s' "$#"; else printf 0; fi
}
marker_state() { # master
    if [ -f "$1/.unsloth-portable-root" ]; then printf present; else printf gone; fi
}
# What the last run reported. Without this the rollback cases would also pass on an
# installer that never touched the launcher at all: "restored" is vacuously true
# when nothing was moved.
said() { # substring
    if grep -qF "$1" "$T/out"; then printf yes; else printf no; fi
}

echo
echo "[1] a successful conversion retires the launcher"
M1="$(new_root)"; build "$M1"
rc="$(convert "$M1/studio" FAIL_MODE=ok)"
check "1 the conversion exits 0" 0 "$rc"
check "1 the marker is gone" gone "$(marker_state "$M1")"
check "1 the portable launcher is gone" gone "$(shim_state "$M1")"
check "1 and no rollback copy is left behind" 0 "$(strays "$M1")"
check "1 and the run said so" yes "$(said "removed the portable launcher at")"
check "1 naming the shim this install writes instead" yes "$(said "this install launches with $M1/studio/bin/unsloth")"

echo
echo "[2] the launcher it would have kept really did re-enter portable mode"
M2="$(new_root)"; build "$M2"
before="$(cat "$M2/bin/unsloth")"
check "2 before the conversion it exports UNSLOTH_PORTABLE=1" 1 "$("$M2/bin/unsloth" studio)"

echo
echo "[3] a failed conversion puts it back, byte for byte"
rc="$(convert "$M2/studio")"
check "3 the failed conversion exits nonzero" 7 "$rc"
check "3 the marker is restored" present "$(marker_state "$M2")"
check "3 the launcher is restored" present "$(shim_state "$M2")"
check "3 with its original contents" "$before" "$(cat "$M2/bin/unsloth")"
check "3 still executable" yes "$([ -x "$M2/bin/unsloth" ] && printf yes || printf no)"
check "3 and still launches the contained install" 1 "$("$M2/bin/unsloth" studio)"
check "3 leaving no rollback copy behind" 0 "$(strays "$M2")"
check "3 the run really moved it before putting it back" yes "$(said "removed the portable launcher at")"
check "3 and reported the restore" yes "$(said "restored the previous launcher at")"

echo
echo "[4] an interrupted conversion restores it too"
M3="$(new_root)"; build "$M3"
rc="$(convert "$M3/studio" FAIL_MODE=signal)"
check "4 the interrupted conversion exits 130" 130 "$rc"
check "4 the launcher is back" present "$(shim_state "$M3")"
check "4 and the marker with it" present "$(marker_state "$M3")"
check "4 no rollback copy is left behind" 0 "$(strays "$M3")"
check "4 the run really moved it before putting it back" yes "$(said "removed the portable launcher at")"
check "4 and reported the restore" yes "$(said "restored the previous launcher at")"

echo
echo "[5] only OUR launcher for THIS install is touched"
# A wrapper that execs a DIFFERENT install's venv. Same generator, same tree,
# different owner: deleting it would cost that install its launch command.
M4="$(new_root)"; OTHER="$(new_root)"
build "$M4" "$OTHER"
rc="$(convert "$M4/studio" FAIL_MODE=ok)"
check "5 a launcher for another install survives" present "$(shim_state "$M4")"
check "5 and the run never claimed otherwise" no "$(said "removed the portable launcher at")"
check "5 and still works" 1 "$("$M4/bin/unsloth" studio)"

# The normal-mode shape at the same path is a symlink, not a wrapper.
M5="$(new_root)"; build "$M5"
rm -f "$M5/bin/unsloth"
ln -s "$M5/studio/unsloth_studio/bin/unsloth" "$M5/bin/unsloth"
rc="$(convert "$M5/studio" FAIL_MODE=ok)"
check "5 a symlink is left alone" symlink "$(shim_state "$M5")"
check "5 with nothing claimed about it" no "$(said "removed the portable launcher at")"

# A user's own script at that path exports nothing of ours.
M6="$(new_root)"; build "$M6"
printf '#!/bin/sh\nexec "%s" "$@"\n' "$M6/studio/unsloth_studio/bin/unsloth" > "$M6/bin/unsloth"
chmod +x "$M6/bin/unsloth"
rc="$(convert "$M6/studio" FAIL_MODE=ok)"
check "5 a launcher that is not portable is left alone" present "$(shim_state "$M6")"

# A sibling install under the same portable root is not this install at all, so
# the early return keeps the whole tree, launcher included.
M7="$(new_root)"; build "$M7"
mkdir -p "$M7/other/unsloth_studio"
rc="$(convert "$M7/other" FAIL_MODE=ok)"
check "5 a sibling install keeps the root's launcher" present "$(shim_state "$M7")"
check "5 and the root's marker" present "$(marker_state "$M7")"

echo
echo "[6] the flat layout needs no RETIREMENT: the new shim lands on the same path"
# <master>/bin IS the normal install's bin there, and `ln -sfn` replaces the
# wrapper in place. This pins the assumption the scoping above rests on.
# It still needs the wrapper PRESERVED for the rollback, on its own slot, since
# `ln -sfn` destroys it and the marker beside it does roll back;
# tests/sh/test_install_portable_flat_shim_rollback.sh is what covers that.
M8="$(new_root)"
mkdir -p "$M8/unsloth_studio/bin" "$M8/bin"
printf '%s\n' "$M8" > "$M8/.unsloth-portable-root"
printf '#!/bin/sh\nexport UNSLOTH_PORTABLE=1\n' > "$M8/bin/unsloth"
ln -sfn "$M8/unsloth_studio/bin/unsloth" "$M8/bin/unsloth" 2>/dev/null
check "6 ln -sfn replaces the wrapper in place" symlink "$(shim_state "$M8")"

echo
if [ "$fails" -eq 0 ]; then
    printf 'ALL PASS\n'
else
    printf '%s FAILURES\n' "$fails"
    exit 1
fi
